### ISSUE TITLE
Please, whether to support Carthage with Bitcode now?

### ISSUE THREAD

**Issue by pangpingfei** [pkluz/PKHUD#119]
As stated in the topic.

**Comment by PGLongo** [comment]
Please can you give me more details? PKHUD is carthage compatible and reading the [documentation](https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos) when the talk about bitcode is for the user section, not the library one. 

So it seems that you have to make some changes in order to use PKHUD and release you app on the  store.

**Comment by pangpingfei** [comment]
@PGLongo 
Thank you! I just saw somebody talked about it in Issues. I tried to archive my app, and succeeded.

But, why not write the Carthage Installation in 'How To' section of this project's documentation？I feel strange.

**Comment by PGLongo** [comment]
You're right! I've updated the README.md
