### ISSUE TITLE
<PKHUD.FrameView 0x7faae2eb1950> is being asked to animate its opacity.

### ISSUE THREAD

**Issue by derdida** [pkluz/PKHUD#50]
Hello, 

when ill try to use your Hud i am always getting the following error:

<PKHUD.FrameView 0x7faae2eb1950> is being asked to animate its opacity. This will cause the effect to appear broken until opacity returns to 1.

Ill try to close the Hud if the Server gets a response after a Alamofire POST request.

Is this a bug? Or another problem here?

Thanks in advance.

**Comment by pkluz** [comment]
Please see Issue Nr. #6 - This is absolutely nothing to worry about at this point in time.

Apple, apparently, when creating `UIVisualEffectView` (that thing that does the blur), did not anticipate it being animated... well it's still a UIView so it should be able to - I'd argue. And it also works flawlessly.

I chose to accept the error, in order to significantly reduce code complexity _and_ have native behavior instead of implementing my own blur effect.
